name: Wintersthorn
favicon: null
layout_spectrum: 0
typography_spectrum: 0
title: 'Winters Thorn Official '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#baffff'
    - '#000000'
    - '#435c5c'
    - '#82b2b2'
    - '#5c7f7f'
  brandStrength: 1
  lightness: 0.3549649210181087
  saturation: 0.059388780035078526
  rhythmicContrast: 0.281412165844813
purpose: []
