name: Wintersthorn
favicon: null
layout_spectrum: 0.5993772652000189
typography_spectrum: 0.3118393875192851
title: 'Winters Thorn Official '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2113689088728279
  lightness: 0.3549649210181087
  saturation: 0.059388780035078526
  rhythmicContrast: 0.281412165844813
purpose: []
